# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Raspby Projects
email: punknight16@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey Everyone! I just got a Raspberry Pi, and my first thought was to use it to show people how to boost their home business by creating a Jekyll blog. I've been wanting to start a blog on reviewing white papers and implementing small open source projects for a while. Using the Raspberry Pi as a lens to focus this idea seems like as good a starting place as any. For those interested in getting involved, here is the git repo:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raspbyprojects.com" # the base hostname & protocol for your site, e.g. http://example.com
absolute_url: "https://raspbyprojects.com"
twitter_username: punknight16
#GitHub services
github_username:  punknight16
github:
  repository_url: https://github.com/punknight16/raspby-projects

#Google services
google_analytics: UA-44077230-8

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
